In [1]:
# import library
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [2]:
#load data
df = pd.read_csv("IndoLeX_Database.csv")
text_column = "category"
#memecah teks jadi kalimat
text = "Saya belajar NLP. NLP sangat menarik. Saya ingin menjadi NLP Engineer."
sentences = sent_tokenize(text)
for sentence in sentences:
    print(sentence)
#Word Tokenization
from nltk.tokenize import word_tokenize
text = "Saya belajar Natural Language Processing."
tokens = word_tokenize(text)
print(tokens)

Saya belajar NLP.
NLP sangat menarik.
Saya ingin menjadi NLP Engineer.
['Saya', 'belajar', 'Natural', 'Language', 'Processing', '.']

In [3]:
#Character Tokenization
text = "NLP"
characters = list(text)
print(characters)

#Menerapkan word tokenization ke seluruh data:
df["tokens"] = df[text_column].fillna("").astype(str).apply(word_tokenize)
df[[text_column, "tokens"]].head()
df["jumlah_token"] = df["tokens"].apply(len)
df["jumlah_token"].describe()

#membandingkan jumlah kata dan token
df["jumlah_kata"] = df[text_column].astype(str).apply(
    lambda x: len(x.split())
)
df[["jumlah_kata", "jumlah_token"]].describe()

['N', 'L', 'P']

       jumlah_kata  jumlah_token
count     131534.0      131534.0
mean           1.0           1.0
std            0.0           0.0
min            1.0           1.0
25%            1.0           1.0
50%            1.0           1.0
75%            1.0           1.0
max            1.0           1.0

In [4]:
texts = [
    "Saya suka produk ini.",
    "Bagus banget!!!",
    "Tidak bagus...",
    "Harga Rp50.000.",
    "email@example.com",
    "https://example.com",
    "yg bagus bgt sih",
    "aku udah beli nih kak"
]

for text in texts:
    print("TEXT :", text)
    print("TOKEN:", word_tokenize(text))
    print()

TEXT : Saya suka produk ini.
TOKEN: ['Saya', 'suka', 'produk', 'ini', '.']

TEXT : Bagus banget!!!
TOKEN: ['Bagus', 'banget', '!', '!', '!']

TEXT : Tidak bagus...
TOKEN: ['Tidak', 'bagus', '...']

TEXT : Harga Rp50.000.
TOKEN: ['Harga', 'Rp50.000', '.']

TEXT : email@example.com
TOKEN: ['email', '@', 'example.com']

TEXT : https://example.com
TOKEN: ['https', ':', '//example.com']

TEXT : yg bagus bgt sih
TOKEN: ['yg', 'bagus', 'bgt', 'sih']

TEXT : aku udah beli nih kak
TOKEN: ['aku', 'udah', 'beli', 'nih', 'kak']

In [5]:
import spacy

# Load model spaCy
nlp = spacy.load("xx_ent_wiki_sm")

# Teks yang akan dibandingkan
texts = [
    "Saya belajar NLP.",
    "Bagus banget!!!",
    "Harga Rp50.000"
]

# Membuat data tabel
data = []

for text in texts:
    # NLTK
    nltk_tokens = word_tokenize(text)

    # split()
    split_tokens = text.split()

    data.append([
        text,
        nltk_tokens,
        split_tokens,
    ])

# Membuat tabel
tabel = pd.DataFrame(
    data,
    columns=[
        "Teks",
        "NLTK word_tokenize",
        "split()",
    ]
)

# Menampilkan tabel
display(tabel)

                Teks        NLTK word_tokenize                split()
0  Saya belajar NLP.   [Saya, belajar, NLP, .]  [Saya, belajar, NLP.]
1    Bagus banget!!!  [Bagus, banget, !, !, !]     [Bagus, banget!!!]
2     Harga Rp50.000         [Harga, Rp50.000]      [Harga, Rp50.000]